---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: 
          - python3-passlib
          - python3-pip
        state: present
        update_cache: yes

    - name: Install SSH key
      authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"