---
- name: Configure Raspberry Pi prerequisites for k3s
  hosts: all
  become: true
  tasks:
    - name: Enable cgroup settings in cmdline.txt
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: '^((?!.*\bcgroup_memory=1 cgroup_enable=memory\b).*)$'
        line: '\1 cgroup_memory=1 cgroup_enable=memory'
      register: cmdline_modified

    - name: Install iptables
      apt:
        name:
          - iptables
          - iptables-persistent
        state: present
        update_cache: yes

    - name: Reboot if cmdline.txt was modified
      reboot:
      when: cmdline_modified.changed